services:
  - type: web
    name: sdcart-backend
    env: linux
    buildCommand: |
      export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
      ./mvnw clean package -DskipTests
    startCommand: java -jar target/sdcart-0.0.1-SNAPSHOT.jar
