services:
  - type: web
    name: sdcart-backend
    runtime: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/sdcart-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://gondola.proxy.rlwy.net:41081/railway
      - key: SPRING_DATASOURCE_USERNAME
        value: root
      - key: SPRING_DATASOURCE_PASSWORD
        value: RnbBqNvCWfTjytXxkydZyBWUrINrCTwc
      - key: JAVA_HOME
        value: /usr/lib/jvm/java-11-openjdk-amd64